name: Sync and Trigger GitLab Pipeline

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync with GitLab and trigger pipeline
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/saeids/challenge"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH:: "true"
          GITLAB_HOSTNAME: "https://gitlab.com"
          GITLAB_USERNAME: "saeids"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "46305849"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Mirror and run GitLab CI

on:
  push:
